### ISSUE TITLE
Update the Meta tag for the https://minteddirectory.com/

### ISSUE THREAD

**Issue by leamsigc** [masterkram/minted-directory#17]
It seems like the https://minteddirectory.com/ is using the default seo meta tags from the Lemonrepo.

useSeoMeta({
  title: "Lemonrepo - Sell access to private GitHub repositories",
  description: "Sell templates, codebases, websites, and more with Lemonrepo.",
  ogImage: "https://supersaas.dev/og-image.png",
});

El cambio seria en el componente App.vue

**Comment by masterkram** [comment]
fixed 👍
